### ISSUE TITLE
Atmospheres are "upside down"

### ISSUE THREAD

**Issue by soordeean** [WazWaz/EnvironmentalVisualEnhancements#13]
![image](https://user-images.githubusercontent.com/39235815/39966000-7ae4091c-56a4-11e8-8104-beb0f4003daa.png)
I'm 99% sure this is a problem with E.V.E. I've tried reinstalling the mod but that doesn't fix it. I'm running ksp version 1.4.2

**Comment by soordeean** [comment]
The "ball" or the atmosphere moves with the camera aswell.

**Comment by WazWaz** [comment]
Any chance you could include a comment when closing an issue, as others might take the same path as you, but not find the solution.
