### ISSUE TITLE
EVE cfg edit bug

### ISSUE THREAD

**Issue by Galileo88** [WazWaz/EnvironmentalVisualEnhancements#2]
Open EVE GUI at KSC or in orbit or anywhere in flight, make any change in the cloudmanager, and hit apply.  You don't even have to make a change just hit apply. Debug menu floods with NullRefs.

Only way to fix the issue is to perform a scene change.

Changing EVE cfgs in tracking station does not cause the above issues.

**Comment by WazWaz** [comment]
I did exactly this: start new game, Alt-0, go to clouds, Apply. Yes, a stream of NullRefs, but they're all from Scatterer, not EVE, and there is no visible problem in-game (i.e. all EVE clouds still look just fine). Tested with both SVE and BoulderCo configs.

Without Scatterer, nothing untoward happens at all.

**Comment by WazWaz** [comment]
I did the same from Flight and saw cloud shadows go wrong. I'll fix that in the next release.
