### ISSUE TITLE
im new to EVE and im not seeing any effects 

### ISSUE THREAD

**Issue by grinches** [WazWaz/EnvironmentalVisualEnhancements#20]
I just downloaded eve and what all i believe to be the dependency, and im not seing any effects. i have the SVE, AVP, and BC but im not able to get them to work. i can see SVE in the UI but no matter what i do nothing shows up. tell me if im missing.

**Comment by WazWaz** [comment]
The issues list is not a place for support. As per the Releases page:

> Please use the forums for discussions. If you are having a problem, ask there. If you have a confirmed bug, post it as an Issue here.
