### ISSUE TITLE
Clouds can entirely hide Resource Overlay (eg. on Eve)

### ISSUE THREAD

**Issue by WazWaz** [WazWaz/EnvironmentalVisualEnhancements#23]
Investigate shader ordering in 1.8.

**Comment by WazWaz** [comment]
They also seem to sometimes go over the main menu GUI text (!!!)

**Comment by mdpkh** [comment]
Clouds always appear in front of main menu GUI text in my game. This issue has been around since before KSP 1.8 was released.

**Comment by WazWaz** [comment]
Fixed by quick option to disable.
