### ISSUE TITLE
Compatibility with KSP 1.9 through CKAN

### ISSUE THREAD

**Issue by metalbass** [WazWaz/EnvironmentalVisualEnhancements#28]
The Compatibility with KSP 1.9 through CKAN would be cool.

Any plans? Do we know what's needed? I could contribute; I have C# unity experience from work.

**Comment by WazWaz** [comment]
Unfortunately, it's shader problems, not C# - see the forums. While it does mostly work, I can't in good conscience say it's "compatible with KSP 1.9". I've attempted to fix the problems, without success.

**Comment by metalbass** [comment]
While shaders are not my specialty, unless it's super advanced, I should be able to understand what's wrong.

Plenty to read on the forums; I'll get myself up to date and see how I can help there :)
