### ISSUE TITLE
My EVE configs don't work

### ISSUE THREAD

**Issue by Geoplex-Official** [WazWaz/EnvironmentalVisualEnhancements#29]
I'm using Ad Astra with JNSQ, and EVE is not working (scatterer is though)
[KSP.log](https://github.com/WazWaz/EnvironmentalVisualEnhancements/files/4854977/KSP.log)
KSP 1.8.1

**Comment by WazWaz** [comment]
Sorry, you'll need to ask the Ad Astra forum for help, since that's where the EVE configs are coming from.

**Comment by Geoplex-Official** [comment]
thanks
