### ISSUE TITLE
Error generated during EVE loading related to AssetBundle files...

### ISSUE THREAD

**Issue by Galenmacil** [WazWaz/EnvironmentalVisualEnhancements#3]
Excerpt from the log file:

_[ERR 00:23:04.771] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:04.771] AssetLoader: Bundle is null

[ERR 00:23:04.821] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:04.821] AssetLoader: Bundle is null

[ERR 00:23:04.871] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:04.871] AssetLoader: Bundle is null

[ERR 00:23:04.921] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:04.921] AssetLoader: Bundle is null

[ERR 00:23:04.971] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:04.971] AssetLoader: Bundle is null

[ERR 00:23:05.021] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:05.021] AssetLoader: Bundle is null

[ERR 00:23:05.071] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:05.071] AssetLoader: Bundle is null

[ERR 00:23:05.238] Trying to reload asset from disk that is not stored on disk

[ERR 00:23:05.276] Trying to reload asset from disk that is not stored on disk

[ERR 00:23:05.294] Trying to reload asset from disk that is not stored on disk

[ERR 00:23:05.381] Trying to reload asset from disk that is not stored on disk

[ERR 00:23:05.401] Trying to reload asset from disk that is not stored on disk

[ERR 00:23:05.457] Trying to reload asset from disk that is not stored on disk

[ERR 00:23:05.488] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:05.488] AssetLoader: Bundle is null

[ERR 00:23:05.538] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:05.538] AssetLoader: Bundle is null

[ERR 00:23:05.587] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:05.587] AssetLoader: Bundle is null

[ERR 00:23:05.638] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:05.638] AssetLoader: Bundle is null

[ERR 00:23:05.687] The AssetBundle 'file://G:\Kerbal Space Program 1.2.0\GameData\EnvironmentalVisualEnhancements\eveshaders-windows.ksp' can't be loaded because another AssetBundle with the same files is already loaded.

[ERR 00:23:05.687] AssetLoader: Bundle is null_

**Comment by WazWaz** [comment]
I intend to look into silencing these - I think they're just a result of using KSP's built-in AssetBundle loader. Are you actually experiencing an EVE-related problem as a result of these?

**Comment by Galenmacil** [comment]
Not that I can tell. I use a custom cloud setup without cities lights that is based on SVE. Everything is looking good...

**Comment by WazWaz** [comment]
This spurious error message should now be gone.
