### ISSUE TITLE
How do I get a config?

### ISSUE THREAD

**Issue by hunterdude44** [WazWaz/EnvironmentalVisualEnhancements#30]

**Comment by WazWaz** [comment]
The sample Configs are not updated with every release, only when they change, as they are quite large. Go back through the Releases and you'll find the most recent one. Alternatively, use another config, such as Stock Visual Enhancements.

You can find these and more details on the KSP EVE Forum page: 

https://forum.kerbalspaceprogram.com/index.php?/topic/149733-18-environmentalvisualenhancements-180-2/
