### ISSUE TITLE
Bug causing the entire bottom half of Kerbin to be filled with CityLights.

### ISSUE THREAD

**Issue by o355** [WazWaz/EnvironmentalVisualEnhancements#7]
Hey,
When I launched KSP today, for some reason, the entire bottom half of Kerbin was filled with the city lights dark texture. Everything was working the other day, I would have probably noticed if an issue had occurred.

Anywhom, removing the CityLights extension from EVE's .dlls, and removing the BoulderCo/CityLights folder looks to have cleared up the issue. Of course, now, there are no actual city lights, but I do believe the city textures still exist. I guess the Kerbin Electric Grid just stopped working.

Anywhom, if this helps, here's the "modlist", as is listed in the GameData folder:

000_Toolbar, 000_USITools, BoulderCo, Coatl Aerospace, CommNetConstellation, CommunityCategoryKit, CommunityResourcePack, CTTP, CustomAsteroids, CustomBarnKit, DistantObject, DMagicOrbitalScience, DMagicScienceAnimate, EnvironmentalVisualEnhancements, Firespitter, HullCameraVDS, JSI, KerbalEngineer, Kopernicus, MechJeb2, ModularFlightIntegrator, OPM, PlanetShine, PreciseManeuver, RealisticAtmospheres, SCANsat, scatterer, Sigma, Squad, SVT, Trajectories, TriggerTech, UmbraSpaceIndustries, and VesselView, along with the usual ModuleManager 2.7.5.

Hope this is enough detail. I'd be happy to send over the full log with CityLights enabled, from startup to me going into the tracking station, if that's needed. I'm running KSP on Windows 10 in 64-bit mode.

**Comment by o355** [comment]
A reinstall fixed the issue. Considering the amount of times I force off my desktop, something was bound to corrupt.

**Comment by WazWaz** [comment]
Did you happen to grab a screenshot before you reinstalled? That can help track things if someone else sees the same thing, as I'm not 100% sure I understand your description.

**Comment by o355** [comment]
I didn't manage to get a screencap of Kerbin's city lights issue, but later I had an issue with textures on Duna/Laythe, and I managed to get screenshots of those. I'll post them when I can.
